version: '3.9'

services:
  apache:
    image: httpd:latest
    container_name: apache-app
    restart: unless-stopped
    ports:
    - '80:80'
    volumes:
    - ./app:/usr/local/apache2/htdocs